### ISSUE TITLE
code for data preprocess

### ISSUE THREAD

**Issue by Master-cai** [PRBonn/retriever#2]
Thanks for your wonderful job! I have some problems with data preprocessing.

- I want to train your project on some other dataset(such as KITTI) and I have compressed the submap into the `npy` files using [depoco](https://github.com/PRBonn/deep-point-map-compression). However, i don\`t know how to generate the `.pickle` file.

- As you provide the precompressed point cloud for `Oxford` and `Inhouse`datasets, what model do you use to compress them?

Could you please provide some code for the data preprocess(like the generation of `.pickle` file)? it will be a great help to me!

Thanks again!

**Comment by louis-wiesmann** [comment]
Hey @Master-cai,

The .pickle files were generated using the original pointnetvlad [code](https://github.com/mikacuy/pointnetvlad/tree/master/generating_queries). 
I always used the [e2](https://github.com/PRBonn/deep-point-map-compression/blob/main/depoco/experiments/results/kitti/e2.pkl) model with 32bit encoding. It gave me usually a compression ratio of 1:100.

**Comment by Master-cai** [comment]
thanks a lot.
