### ISSUE TITLE
Oxford dataset

### ISSUE THREAD

**Issue by YYYY1213800** [PRBonn/retriever#3]
Thank you for your great work. I have studied your Depoco paper before, and I noticed that you used Oxford and In-house data sets here . I am wondering if these data sets were also obtained by converting them into kitti format, then transformerd into the original data submap according to kitti2voxel.py method,  and then comcompressed and encoded the point cloud to the oxford compressed. like what you did for nuScenes datasets.Could you please tell me some details about it.
Thanks a lot

**Comment by louis-wiesmann** [comment]
I directly used the data provided by pointnetvlad for fair comparison. This data is already accumulated and voxelized. As well as the ground plane is removed. 

I would have used a similar script as kitti2voxel if not for comparing against the other baselines which all use the preprocessed data from pointnetvlad
